repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black

  - repo: local
    hooks:
      -   id: pytest
          name: API tests
          entry: pytest -m "api"
          language: python
          types: [python]
