repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: unittest
        name: "Run api tests"
        entry: python -m unittest discover -k "api"
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: unittest
        name: "Run actual todo"
        entry: python -m unittest discover -k "test_model_preprocess_for_training"
        language: python
        types: [python]