version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8000"
      UVICORN_TIMEOUT_KEEP_ALIVE: "120"
    restart: unless-stopped